'\" t
.\"     Title: buildinfo
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 2020-06-25
.\"    Manual: Pacman Manual
.\"    Source: Pacman 5.2.2
.\"  Language: English
.\"
.TH "BUILDINFO" "5" "2020\-06\-25" "Pacman 5\&.2\&.2" "Pacman Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
BUILDINFO \- Makepkg package build information file
.SH "SYNOPSIS"
.sp
This manual page describes the format of a BUILDINFO file found in the root of a package created by makepkg\&. The file contains a description of the package\(cqs build environment\&. The information is formatted in key\-value pairs separated by a \fI=\fR, one value per line\&. Arrays are represented multiple keys with the same value\&.
.SH "DESCRIPTION"
.sp
This is a description of the contents of version \fI1\fR of the BUILDINFO file format\&.
.PP
\fBformat\fR
.RS 4
Denotes the file format version, represented by a plain positive integer\&.
.RE
.PP
\fBpkgname\fR
.RS 4
The name of the package\&.
.RE
.PP
\fBpkgbase\fR
.RS 4
The base name of a package, usually the same as the pkgname except for split packages\&.
.RE
.PP
\fBpkgver\fR
.RS 4
The version of the package including pkgrel and epoch\&.
.RE
.PP
\fBpkgarch\fR
.RS 4
The architecture of the package\&.
.RE
.PP
\fBpkgbuild_sha256sum\fR
.RS 4
The sha256sum in hex format of the PKGBUILD used to build the package\&.
.RE
.PP
\fBpackager\fR
.RS 4
The details of the packager that built the package\&.
.RE
.PP
\fBbuilddate\fR
.RS 4
The build date of the package in epoch\&.
.RE
.PP
\fBbuilddir\fR
.RS 4
The directory where the package was built\&.
.RE
.PP
\fBbuildenv (array)\fR
.RS 4
The build environment specified in makepkg\&.conf\&.
.RE
.PP
\fBoptions (array)\fR
.RS 4
The options set specified when building the package\&.
.RE
.PP
\fBinstalled (array)\fR
.RS 4
The installed packages at build time including the version information of the package\&. Formatted as "$pkgname\-$pkgver\-$pkgrel\-$pkgarch"\&.
.RE
.SH "SEE ALSO"
.sp
\fBmakepkg\fR(8), \fBpacman\fR(8), \fBmakepkg.conf\fR(5)
.sp
See the pacman website at https://www\&.archlinux\&.org/pacman/ for current information on pacman and its related tools\&.
.SH "BUGS"
.sp
Bugs? You must be kidding; there are no bugs in this software\&. But if we happen to be wrong, submit a bug report with as much detail as possible at the Arch Linux Bug Tracker in the Pacman section\&.
.SH "AUTHORS"
.sp
Current maintainers:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Allan McRae <allan@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Andrew Gregory <andrew\&.gregory\&.8@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Dan McGee <dan@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Dave Reisner <dreisner@archlinux\&.org>
.RE
.sp
Past major contributors:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Judd Vinet <jvinet@zeroflux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Aurelien Foret <aurelien@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Aaron Griffin <aaron@archlinux\&.org>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Xavier Chantry <shiningxc@gmail\&.com>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Nagy Gabor <ngaba@bibl\&.u\-szeged\&.hu>
.RE
.sp
For additional contributors, use git shortlog \-s on the pacman\&.git repository\&.
